### ISSUE TITLE
Tokens exceeded for small dataset

### ISSUE THREAD

**Issue by DrDavidL** [Ngonie-x/langchain_csv#3]
Thoughts?

InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 4255 tokens (3999 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

Also - some preprocessing of CSV's to ensure other character errors don't arise would be ideal.  :) I'm trying to do some of this, too! Thank you so much for this great work!

**Comment by Ngonie-x** [comment]
Glad you liked the article!

The invalid request error means your request exceeded the maximum context length of 4097 tokens. The context length is the total number of tokens in your prompt and the completion. The maximum allowed context length for the Open AI model is 4097 tokens, so your request was rejected. To fix it, reduce the length of your prompt or completion.

Here are some additional tips for fixing the invalid request error:
- Remove any unnecessary text from your prompt.
- Request a shorter completion.
- Specify which columns you want to be considered.
- Limit the number of records returned.

Thanks for your suggestion! I agree that preprocessing CSVs is a good idea to ensure that other character errors don't arise. I'll take a look at the issue and see if I can implement it but if you are able to implement it, you are free to contribute to the project. I would be happy to review your changes and merge them into the main codebase!
